[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      font-src 'self' https://*.netlify.app fonts.gstatic.com gstatic.com *.gstatic.com;
      script-src 'self' https://*.cloudfront.net https://*.netlify.app *.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://*.netlify.app https://*.cloudfront.net https://fonts.googleapis.com;
      frame-src *.netlify.app https://wallet.arcana.network https://wallet.beta.arcana.network https://wallet.dev.arcana.network https://karthik-click-jacking-issue-toml-edit--wallet-dev.netlify.app https://feature-permission-tab-with-toml-edit--wallet-verify-dev.netlify.app https://app.netlify.com;
      frame-ancestors 'self';
    '''

[[headers]]
  for = "/assets/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      font-src self fonts.gstatic.com https://*.netlify.app gstatic.com *.gstatic.com;
      script-src 'self' https://*.netlify.app https://*.cloudfront.net *.googletagmanager.com;;
      style-src 'self' 'unsafe-inline' https://*.netlify.app https://*.cloudfront.net https://fonts.googleapis.com;
      frame-src *.netlify.app https://wallet.arcana.network https://wallet.beta.arcana.network https://wallet.dev.arcana.network https://karthik-click-jacking-issue-toml-edit--wallet-dev.netlify.app https://feature-permission-tab-with-toml-edit--wallet-verify-dev.netlify.app https://app.netlify.com;
      frame-ancestors 'self';
    '''
    cache-control = "max-age=31536000, immutable"

